---
title: "Report Template for Audited Phenotype Files"
output:
  html_document:
    code_folding: hide
  highlight: tango
  number_sections: no
  theme: default
  toc: yes
  toc_depth: 3
  toc_float:
    collapsed: no
    smooth_scroll: yes
  params:
    dataset.name: ""
    variable.summary: NULL
    phenotype.data: ""
---

## Load required R packages

```{r load.packages, eval=TRUE, echo=FALSE}
library(ggplot2, quietly = TRUE)
library(knitr, quietly = TRUE)
library(kableExtra, quietly = TRUE)
```

***
<br>

## Configure default ggplot2 theme for plotting

```{r configure.ggplot2.theme, eval=TRUE, echo=FALSE}
my.theme <- theme_light() + theme(
  plot.title = element_text(size = 16, hjust = 0.5),
  axis.title = element_text(size = 14),
  axis.text = element_text(size = 12),
  strip.background = element_blank(),
  strip.text = element_text(size = 14, colour = "black"),
  legend.title = element_text(size = 14),
  legend.text = element_text(size = 13)
)
```

***
<br>

## Report linking between input and standardized variable names

```{r report.variable.mappings, eval=TRUE, echo=FALSE, results="asis"}
variable.mapping.df <- data.frame(
  names(variable.summary),
  sapply(variable.summary, function(i) {
    i$original.name
  })
)
rownames(variable.mapping.df) <- NULL
colnames(variable.mapping.df) <- c("Standardized", "Original")
knitr::kable(variable.mapping.df, caption = "Phenotype Variable Names")
```

***
<br>

## Report all unique values for string variables

```{r report.value.summary, eval=TRUE, echo=FALSE, results="asis"}
for (name in names(variable.summary)) {
  my.summ <- variable.summary[[name]]$summary
  ## if the source data type is numeric
  if (is.vector(phenotype.data[, name], mode = "numeric")) {
    ## create data histogram for numeric data
    plot.data <- data.frame(x = phenotype.data[, name])
    hist.plot <- ggplot(data = plot.data) + my.theme
    binwidth <- diff(quantile(plot.data$x, probs = c(0.5, 0.75), na.rm = TRUE)) / 12.5
    hist.plot <- hist.plot + geom_histogram(
      aes(x = x, y = ..count.. / sum(..count..)),
      binwidth = binwidth
    )
    hist.plot <- hist.plot + xlab(name) + ylab("proportion of data")
    hist.plot <- hist.plot + ggtitle(paste("Histogram of ", name, " (",
      variable.summary[[name]]$original.name,
      ") Distribution",
      sep = ""
    ))
    print(hist.plot)
  }
  ## original exclusion criterion here is hitting everything for small datasets,
  ## even when the report is not a unique value report
  if (is.vector(phenotype.data[, name], mode = "numeric") |
    length(my.summ) < nrow(phenotype.data) / 10) {
    variable.summary.df <- data.frame(
      names(my.summ), as.vector(my.summ)
    )
    rownames(variable.summary.df) <- NULL
    colnames(variable.summary.df) <- c("Value", "Summary statistics")
    print(knitr::kable(variable.summary.df, caption = paste("Summary of ", name, " (", variable.summary[[name]]$original.name, ")", sep = "")))
  }
  if (variable.summary[[name]]$blood.pressure.detected) {
    print("This variable was automatically detected as blood pressure measurements (SBP/DBP).")
    if (length(variable.summary[[name]]$invalid.blood.pressure.entries) > 0) {
      df <- data.frame(table(variable.summary[[name]]$invalid.blood.pressure.entries, useNA = "ifany"))
      rownames(df) <- NULL
      colnames(df) <- c(name, "Count")
      print(knitr::kable(df, caption = "Values that were not consistent with blood pressure measurement format."))
    } else {
      print("All values were consistent with blood pressure measurement format.")
    }
  }
}
```

***
<br>

## Session Information

<br>

The following summarizes the loaded R configuration for the run that created this report.

```{r session.info, eval=TRUE, echo=TRUE}
sessionInfo()
```
